Support mutations & subscriptions in NQ -> AST compiler
graphql-java/graphql-java pull request #2417
Opened 2021-07-02 04:02 UTC by gnawf

2021-07-02 04:23 UTC, temaEmelyan approved these changes

2021-07-02 05:05 UTC, andimarek requested changes
I think this is not the right approach as it now requires a Schema object.

2021-07-02 05:05 UTC, andimarek commented on src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
> +                throw Assert.<RuntimeException>assertShouldNeverHappen("Top level selection must be an inline fragment");
this looks like a non needed type Qualifer <RuntimeException>

2021-07-02 05:05 UTC, andimarek commented on src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
> +    public static Document compileToDocument(GraphQLSchema schema, List<ExecutableNormalizedField> topLevelFields) {
We should not need a schema to print a NormalizedOperation. I think we need to add the operation to the `ExecutableNormalizedOperation` itself or pass it here into the function.

2021-07-06 00:18 UTC, andimarek approved these changes

2021-07-06 00:25 UTC, merged