Bugfix: don't fail document validation when nullable type is provided in the query for non-nullable argument with default argument value specified in the schema.
graphql-java/graphql-java pull request #2573
Opened 2021-10-05 13:13 UTC by folone

### Problem

Graphql-java currently fails the document validation for queries that use nullable types for non-nullable schema field arguments with default values. As per [spec](https://spec.graphql.org/June2018/#sec-All-Variable-Usages-are-Allowed):
> A notable exception to typical variable type compatibility is allowing a variable definition with a nullable type to be provided to a non‐null location as long as either that variable or that location provides a default value.

## Motivating example:

Schema:
```
type Query {
  hello(arg: Boolean! = true)
}
```

Query:
```
query Test($var: Boolean) {
  hello(arg: $var)
}
```

Should validate as per spec, but fails:
`ValidationError{validationErrorType=VariableTypeMismatch, queryPath=[hello], message=Validation error of type VariableTypeMismatch: Variable type 'Boolean' doesn't match expected type 'Boolean!' @ 'hello', locations=[SourceLocation{line=3, column=25}], description='Variable type 'Boolean' doesn't match expected type 'Boolean!''}`

### Solution

This patch fixes the issue by extracting the schema-defined default value for the argument, and checks that in the `VariablesTypeMatcher` along with the original check. This also adds a regression test to exercise this fix.

2021-10-05 15:38 UTC, jbellenger commented
Related to this, here's [a test case in graphql-js](https://github.com/graphql/graphql-js/blob/main/src/execution/__tests__/variables-test.ts#L994-L1008) for this behavior

2021-12-20 03:56 UTC, andimarek commented on src/main/java/graphql/validation/rules/VariableTypesMatchRule.java
> +        }
You can simplify the code here: there is a method in ValuesResolver `ValuesResolver.valueToLiteral` which takes care of converting it fo you.

2021-12-20 04:00 UTC, andimarek requested changes
Thanks for that. Please have a look a the comment I left.

2021-12-22 12:04 UTC, folone commented on src/main/java/graphql/validation/rules/VariableTypesMatchRule.java
> +        }
Hey @andimarek! I believe that's the exact method I'm using on line 67 there. Am I missing something else?

2021-12-27 03:44 UTC, merged