Stop DOS attacks by making the lexer stop early on evil input.
graphql-java/graphql-java pull request #2892
Opened 2022-07-21 08:48 UTC by bbakerman

This is related to #2888

The bug was that we do indeed have a max token counting mechanism in graphql-java

2022-07-21 11:45 UTC, bbakerman commented
The questions to be answered here is whether to track the whitespace and line comment channels or not.  They are fast BUT they still take some time BUT not like the grammar channel does.

when we run the ParserBadSituations program with unlimited tokens the numbers for whitespace and comments are something like

```

Whitespace Bad Payloads(run #2)(1 of 15) - | query length 50020 | bad payloads 5000 | duration 4ms 
Whitespace Bad Payloads(run #2)(2 of 15) - | query length 100020 | bad payloads 10000 | duration 9ms 
Whitespace Bad Payloads(run #2)(3 of 15) - | query length 150020 | bad payloads 15000 | duration 16ms 
Whitespace Bad Payloads(run #2)(4 of 15) - | query length 200020 | bad payloads 20000 | duration 19ms 
Whitespace Bad Payloads(run #2)(5 of 15) - | query length 250020 | bad payloads 25000 | duration 28ms 
Whitespace Bad Payloads(run #2)(6 of 15) - | query length 300020 | bad payloads 30000 | duration 28ms 
Whitespace Bad Payloads(run #2)(7 of 15) - | query length 350020 | bad payloads 35000 | duration 50ms 
Whitespace Bad Payloads(run #2)(8 of 15) - | query length 400020 | bad payloads 40000 | duration 41ms 
Whitespace Bad Payloads(run #2)(9 of 15) - | query length 450020 | bad payloads 45000 | duration 46ms 
Whitespace Bad Payloads(run #2)(10 of 15) - | query length 500020 | bad payloads 50000 | duration 48ms 
Whitespace Bad Payloads(run #2)(11 of 15) - | query length 550020 | bad payloads 55000 | duration 55ms 
Whitespace Bad Payloads(run #2)(12 of 15) - | query length 600020 | bad payloads 60000 | duration 52ms 
Whitespace Bad Payloads(run #2)(13 of 15) - | query length 650020 | bad payloads 65000 | duration 87ms 
Whitespace Bad Payloads(run #2)(14 of 15) - | query length 700020 | bad payloads 70000 | duration 84ms 
Whitespace Bad Payloads(run #2) - finished | max time was 87 ms 
=======================

Comment Bad Payloads(run #2)(1 of 15) - | query length 75022 | bad payloads 5000 | duration 14ms 
Comment Bad Payloads(run #2)(2 of 15) - | query length 150022 | bad payloads 10000 | duration 25ms 
Comment Bad Payloads(run #2)(3 of 15) - | query length 225022 | bad payloads 15000 | duration 31ms 
Comment Bad Payloads(run #2)(4 of 15) - | query length 300022 | bad payloads 20000 | duration 34ms 
Comment Bad Payloads(run #2)(5 of 15) - | query length 375022 | bad payloads 25000 | duration 26ms 
Comment Bad Payloads(run #2)(6 of 15) - | query length 450022 | bad payloads 30000 | duration 25ms 
Comment Bad Payloads(run #2)(7 of 15) - | query length 525022 | bad payloads 35000 | duration 32ms 
Comment Bad Payloads(run #2)(8 of 15) - | query length 600022 | bad payloads 40000 | duration 37ms 
Comment Bad Payloads(run #2)(9 of 15) - | query length 675022 | bad payloads 45000 | duration 48ms 
Comment Bad Payloads(run #2)(10 of 15) - | query length 750022 | bad payloads 50000 | duration 51ms 
Comment Bad Payloads(run #2)(11 of 15) - | query length 825022 | bad payloads 55000 | duration 48ms 
Comment Bad Payloads(run #2)(12 of 15) - | query length 900022 | bad payloads 60000 | duration 48ms 
Comment Bad Payloads(run #2)(13 of 15) - | query length 975022 | bad payloads 65000 | duration 52ms 
Comment Bad Payloads(run #2)(14 of 15) - | query length 1050022 | bad payloads 70000 | duration 70ms 
Comment Bad Payloads(run #2) - finished | max time was 70 ms 
=======================
````

So it starts to creep up BUT nothing like the grammar file which is 2 orders of magnitude slower!

2022-07-22 05:13 UTC, bbakerman commented
After chats with Andi and Donna, we decided to

* add a separate whitespace max token count - this is set at 200_000 whitespace tokens
* add a separate set of default parser options for "operation" parsing versus DSL
   *  We don't want comment lines captured by default on operation AST elements

2022-07-26 00:22 UTC, andimarek requested changes
1: Small naming change 

2: I think with introducing defaultOperationParserOptions we should rethink the `SchemaParser.parseImpl` where we overwrite the `maxTokens`. I think we don't need this anymore if we have two different ParserOptions.

2022-07-26 00:22 UTC, andimarek commented on src/main/java/graphql/parser/Parser.java
> +    @Internal
lets call this also whitespace channel and not ignored ones to make it consistent with the options.

2022-07-26 00:22 UTC, andimarek commented on src/main/java/graphql/parser/ParserOptions.java
I think we should name this `SDL` parser options or so to make clear it will be used for Schema Parsing. See also my general review comment.

2022-07-26 05:42 UTC, merged

2022-07-29 22:40 UTC, bbakerman commented
> Do you have( or are planning to create) a CVE for this?

We don't have concrete plans - mainly because we are unsure of the process and the work involved.

If you know more about this works and could coach us on process that would great because we aren't against the idea, we just know very little about the how of it

2022-08-03 11:21 UTC, act1on3 commented
Hi @bbakerman ,
I've sent CVE request with the form: https://cveform.mitre.org/
I'll let you know about changes.

2022-09-14 04:31 UTC, dondonz commented
@act1on3 I'd like to update the CVE with all versions containing the fix: v19.0/19.1/19.2, v18.3, and v17.4.

I've never had to update a CVE before - do you have any way to edit the text from your end?

2022-09-14 07:52 UTC, act1on3 commented
Hi @dondonz ,
I believe an analyst from MITRE updated it already. Thanks for info.

2022-09-14 09:07 UTC, yeikel commented
Considering the different packports, is the range correct? Ie: are users with 17.x  versions that have the backport vulnerable?

2022-09-14 23:07 UTC, dondonz commented
Thanks @act1on3, I ended up contacting MITRE to fix it.

@yeikel Yes version v17.4 contains the backport, see the release notes https://github.com/graphql-java/graphql-java/releases/tag/v17.4

2022-09-14 23:50 UTC, yeikel commented
> Thanks @act1on3, I ended up contacting MITRE to fix it.
> 
> @yeikel Yes version v17.4 contains the backport, see the release notes https://github.com/graphql-java/graphql-java/releases/tag/v17.4

If that's the case, then we should explicitly state that in the CVE. Otherwise, scanning systems will flag versions that are safe

2022-09-15 00:56 UTC, dondonz commented
@yeikel I agree, I'm getting automated tickets myself at work. The CVE text has been updated to reference the backported versions.

```
graphql-java before19.0 is vulnerable to Denial of Service. An attacker can send a malicious GraphQL query that consumes CPU resources. The fixed versions are 19.0 and later, 18.3, and 17.4.
```
https://www.cve.org/CVERecord?id=CVE-2022-37734

I am also speaking to Snyk to fix their recommendation.