Enable selection set analysis before field resolution starts
graphql-java/graphql-java pull request #3174
Opened 2023-04-10 01:06 UTC by kaqqao

`ExecutableNormalizedOperation` enables accurate complexity analysis of the entire (multi-root?) query before any field resolution starts, but it is an internal class. On the other hand, `DataFetchingFieldSelectionSet` exposes all the necessary info, and is public, but is only created for an individual field once field resolution starts, and it is thus impossible to use it to analyze the entire query and completely prevent execution if a condition matches e.g. from `Instrumentation#beginExecuteOperation`.

With this PR, a `DataFetchingFieldSelectionSet` is (lazily) created for each root field before field resolution. The list is then made accessible via `ExecutionContext`, so it is possible to retrieve it from an instrumentation at any stage where `ExecutionContext` exists, such as `beginExecuteOperation`. This way all the interesting information from the normalized query tree (i.e. `ExecutableNormalizedOperation`) is exposed to complexity analysis as early as the query tree itself exists, but without exposing either the tree or any other private API.

I am not exactly sure this is the correct approach, but might at least serve to start the conversation.

Fixes #1695

2023-04-10 01:12 UTC, kaqqao commented on src/main/java/graphql/execution/ExecutionContext.java
> +        this.rootDataFetchingFieldSelectionSet = FpKit.intraThreadMemoize(() -> collectRootDataFetchingFieldSelectionSets(queryTree, builder.graphQLSchema));
Intra-thread as the creating `DataFetchingFieldSelectionSet` isn't an expensive operation in itself to warrant synchronized access. But that might be a wrong conclusion.

2023-04-10 01:12 UTC, kaqqao commented on src/main/java/graphql/execution/ExecutionContext.java
> +                root.getFieldDefinitions(schema).get(0).getType(), //root fields always have a single parent
This is, I believe, safe. All root fields have a singular parent, introspection fields included. Right?

2023-04-11 08:13 UTC, bbakerman commented
I am supportive of this - eg making the top level field selection sets available

However this PR needs way more tests to be acceptable

The magic fields (`__typename`, `__schema` etc..) need to be included to make sure this works

And we need some complex queries with nest levels to just make sure we build what we think we have built.

2023-04-11 08:14 UTC, bbakerman requested changes
See my comments on what is needed for this to be acceptable

2023-04-13 19:44 UTC, kaqqao commented
My main intention with this PR was to expose the info from ENF, without exposing ENF itself. With ENF becoming public (🥳), I don't think adding this is particularly useful, so I'll close the PR. But if you disagree, I'll clean it up as you asked and reopen.

2023-04-13 19:44 UTC, closed without merging