add a default max nodes count for the ExecutableNormalizedFactory
graphql-java/graphql-java pull request #3547
Opened 2024-03-26 07:13 UTC by andimarek

The ENOF should have a default max nodes, which is high, but still prevents a to large memory creation

2024-03-26 07:19 UTC, bbakerman commented on src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
> +                    100_000,
We should have a JVM static way of getting / setting this default - like we do in other places

See `graphql.parser.ParserOptions#MAX_WHITESPACE_TOKENS` for inspiration

2024-03-26 07:19 UTC, bbakerman requested changes
Look to put javadoc and a static set of getters and setters in place

2024-03-26 23:51 UTC, andimarek commented
@bbakerman have a look again

2024-03-27 05:28 UTC, bbakerman approved these changes

2024-03-27 05:30 UTC, merged